# Copy the Stata reference tables into the package as committed test fixtures.
#
# The CSVs in this directory need a Stata licence to produce. Committing them
# into the package turns the parity suite from "skips unless you have Stata"
# into "runs everywhere", which is the point: the tables are evidence about the
# original implementation, and evidence is worth keeping.
#
# The .csv files here are written by `export delimited` at full double
# precision (17 significant digits), so this is a validating copy rather than a
# reformat -- rounding would put the exact-arithmetic test out of reach.
#
# Run from this directory after regenerating any of the .do files:
#     Rscript make-fixtures.R
#
# It refuses to write a partial set. Grid 5 must be regenerated alongside the
# others, because the exact test joins its fits to the design grids on dataset,
# model, scale, subset and nocontvar; a stale grid 5 silently compares against
# the wrong fit.

STEMS <- c("01_grid_arithmetic", "02_grid_comparators", "03_grid_fits",
           "04_edge_cases", "05_variance_components")

# Row counts as generated on 2026-08-04. A mismatch means a .do file changed
# without this manifest being updated, which is exactly when a stale fixture
# would otherwise slip through unnoticed.
EXPECTED_ROWS <- c("01_grid_arithmetic" = 348, "02_grid_comparators" = 88,
                   "03_grid_fits" = 77, "04_edge_cases" = 71,
                   "05_variance_components" = 37)

here <- normalizePath(".")
dest <- normalizePath(file.path(here, "..", "slopepower", "tests", "testthat",
                                "fixtures"), mustWork = FALSE)

missing <- STEMS[!file.exists(file.path(here, paste0(STEMS, ".csv")))]
if (length(missing)) {
  stop("missing reference CSVs: ", paste(missing, collapse = ", "),
       "\nRun the corresponding .do files under Stata first.")
}

dir.create(dest, recursive = TRUE, showWarnings = FALSE)

manifest <- data.frame(stem = STEMS, rows = NA_integer_, cols = NA_integer_,
                       stringsAsFactors = FALSE)

for (i in seq_along(STEMS)) {
  stem <- STEMS[i]
  src <- file.path(here, paste0(stem, ".csv"))
  x <- utils::read.csv(src, stringsAsFactors = FALSE, na.strings = c("NA", "."))

  if (nrow(x) != EXPECTED_ROWS[[stem]]) {
    stop(sprintf("%s has %d rows, manifest expects %d. If the .do file changed
on purpose, update EXPECTED_ROWS in this script.",
                 stem, nrow(x), EXPECTED_ROWS[[stem]]))
  }

  # Grid 5 is the reference for the exact test, so a fit that did not converge
  # would poison it silently.
  if (stem == "05_variance_components" && !all(x$converged == 1)) {
    stop("05_variance_components contains non-converged fits: ",
         paste(x$vtag[x$converged != 1], collapse = ", "))
  }

  file.copy(src, file.path(dest, paste0(stem, ".csv")), overwrite = TRUE)
  manifest$rows[i] <- nrow(x)
  manifest$cols[i] <- ncol(x)
  cat(sprintf("%-24s %4d rows x %2d cols\n", stem, nrow(x), ncol(x)))
}

writeLines(
  c("# Stata reference fixtures",
    "#",
    "# Generated by stata-reference/make-fixtures.R from the CSVs written by",
    "# the .do files in that directory. Do not edit by hand: regenerate.",
    "#",
    paste0("# Generated: ", format(Sys.Date())),
    "",
    paste(manifest$stem, manifest$rows, manifest$cols, sep = ",")),
  file.path(dest, "MANIFEST")
)

cat("\nwrote", nrow(manifest), "fixtures to", dest, "\n")
