# Reading the golden-reference tables generated by ../stata-reference/*.do.
#
# The paper gives 15 numbers. These tables give a few hundred, spread over the
# corners of the option space the paper never visits: irregular schedules,
# dropout patterns that pile up at one visit, effectiveness and alpha away from
# their defaults, saturating power, subsets that re-origin time, and the three
# comparator branches crossed with both directions of the solve.
#
# The tables are not committed --- they need a Stata licence to produce --- so
# every test built on them skips cleanly when the CSVs are absent.

# The fixtures committed under tests/testthat/fixtures/ are the copies the
# suite normally reads: they need no Stata licence, so the parity tests run
# everywhere rather than skipping on most machines. ../stata-reference/ is the
# fallback, used when regenerating -- point the suite at freshly produced CSVs
# by deleting the fixtures or running make-fixtures.R.
stata_reference_dir <- function() {
  # test_path() throws outside a testthat run; fall back so the helper is
  # usable from an ad-hoc script too.
  base <- tryCatch(testthat::test_path(), error = function(e) ".")
  fx <- file.path(base, "fixtures")
  if (dir.exists(fx)) return(normalizePath(fx))
  d <- paper_data_dir()
  if (is.null(d)) return(NULL)
  p <- file.path(d, "stata-reference")
  if (dir.exists(p)) normalizePath(p) else NULL
}

have_stata_reference <- function(stem) {
  d <- stata_reference_dir()
  !is.null(d) && file.exists(file.path(d, paste0(stem, ".csv")))
}

skip_without_stata_reference <- function(stem) {
  testthat::skip_if_not(
    have_stata_reference(stem),
    sprintf("stata-reference/%s.csv not found; run the .do file under Stata", stem)
  )
}

#' Read one reference table
#'
#' Blank strings come back as "" rather than NA so that `nzchar()` is the only
#' emptiness test anywhere in this file.
read_stata_reference <- function(stem) {
  path <- file.path(stata_reference_dir(), paste0(stem, ".csv"))
  x <- utils::read.csv(path, stringsAsFactors = FALSE, na.strings = c("NA", "."))
  # Grid 5 carries a different column set from the four design grids -- it has
  # one row per fit, not per call -- so normalise whichever of these it has.
  for (col in c("tag", "vtag", "dataset", "model", "subset", "sched", "drops",
                "effin", "mode", "colnames")) {
    if (is.null(x[[col]])) next
    x[[col]][is.na(x[[col]])] <- ""
    x[[col]] <- trimws(x[[col]])
  }
  x
}

# ---------------------------------------------------------------------------
# Reconstructing the R-side call from one row
# ---------------------------------------------------------------------------

# Stata divides the time variable by scale() before fitting and then works on a
# unit integer grid, so a schedule entry j sits at time j * scale on the axis
# Stata was handed. The R helper hands slpower2's time to the fit already
# divided by 365; the other two datasets are handed their time variable raw.
stata_time_divisor <- function(dataset) if (dataset == "slpower2") 365 else 1

# Stata reports the slope on the axis it fitted on, which is the R port's axis
# divided by this factor. So `slope_stata == slope_R * stata_axis_factor`, and
# likewise for the comparator slope and for tte; var_tte carries the square.
# Everything scale-invariant --- N, power, the standardised effect size --- is
# unaffected, which is why the scale sweep in grid 3 matched on N while the
# reported slopes looked wrong by a factor of up to 1000.
stata_axis_factor <- function(row) row$scale / stata_time_divisor(row$dataset)

#' Visit times, on the R port's time axis, for one reference row
stata_visits <- function(row) {
  sched <- as.numeric(strsplit(row$sched, "[[:space:]]+")[[1]])
  c(0, sched) * stata_axis_factor(row)
}

#' Incremental dropout proportions, or NULL
stata_dropout <- function(row) {
  if (!nzchar(row$drops)) return(NULL)
  as.numeric(strsplit(row$drops, "[[:space:]]+")[[1]])
}

# Fitting is the slow part and many rows share a fit, so cache on everything
# that can change one. `scale` is deliberately absent: Stata rescales the time
# variable and refits, while the R port always fits on the axis it was given and
# expresses the visits in those units instead. That the two agree across a range
# of scales is the thing grid 3 is testing, so the R side must not quietly
# rescale to match.
stata_fit_key <- function(row) {
  paste(row$dataset, row$model, row$subset, row$contvar, sep = "|")
}

stata_fit <- function(row) {
  cache <- sp_fit_cache()
  key <- paste0("stata:", stata_fit_key(row))
  if (!is.null(cache[[key]])) return(cache[[key]])

  d <- load_paper_data(row$dataset)

  if (nzchar(row$subset)) {
    keep <- eval(parse(text = row$subset), d)
    d <- d[!is.na(keep) & keep, , drop = FALSE]
  }

  # Stata's scale() rescales the time variable before fitting. The R port has
  # no scale argument: it fits on the axis it is given and expresses visits in
  # those units instead. Both routes must give the same answer, and the visit
  # times from stata_visits() are the "fit on the original axis" route.
  cv <- if (isTRUE(row$contvar == 1)) TRUE else NULL

  fit <- suppressMessages(suppressWarnings(switch(
    row$model,
    obs_nocont = slope_params(sdmt ~ time | id, d),
    obs_cases  = slope_params(sdmt ~ time | id, d, healthy = case,
                              common_variance = cv),
    rct        = slope_params(sdmt ~ time | id, d, treated = treat),
    stop("unknown model: ", row$model)
  )))

  cache[[key]] <- fit
  fit
}

#' Run one reference row through the R port
#'
#' Returns a one-row data frame with the same output columns as the Stata
#' table, or a row of NAs plus the condition message if the R side refused the
#' input. Refusals are data: several of them are the deliberate divergences
#' this port introduced, and the comparison reports rather than hides them.
stata_replay <- function(row) {
  blank <- data.frame(
    r_error = NA_character_, r_n = NA_real_, r_power = NA_real_,
    r_effectiveness = NA_real_, r_tte = NA_real_, r_var_tte = NA_real_,
    r_slope = NA_real_, r_slope_comp = NA_real_,
    r_obs = NA_real_, r_subjects = NA_real_,
    stringsAsFactors = FALSE
  )

  out <- tryCatch({
    p <- stata_fit(row)
    # The baseline-only-dropout warning fires on every "front-loaded" row of
    # grid 1 by design; it is the behaviour under test, not a surprise.
    des <- suppressWarnings(trial_design(stata_visits(row), stata_dropout(row)))

    args <- list(params = p, design = des, alpha = row$alpha)
    if (isTRUE(row$usetrt == 1)) {
      args$target <- "observed"
    } else if (nzchar(row$effin)) {
      args$effectiveness <- as.numeric(row$effin)
    }

    res <- suppressWarnings(
      if (row$mode == "n") do.call(slope_power, c(args, list(n = row$nin)))
      else                 do.call(slope_sample_size, c(args, list(power = row$pin)))
    )

    # Put the R answers on Stata's axis so the two are directly comparable.
    f <- stata_axis_factor(row)
    blank$r_n <- res$n
    blank$r_power <- res$power
    blank$r_effectiveness <- res$effectiveness
    blank$r_tte <- res$tte * f
    blank$r_var_tte <- res$var_tte * f^2
    blank$r_slope <- p$slope * f
    blank$r_slope_comp <- p$slope_comparator * f
    blank$r_obs <- p$n_obs
    blank$r_subjects <- p$n_subjects
    blank
  }, error = function(e) {
    blank$r_error <- conditionMessage(e)
    blank
  })

  out
}

#' Replay every row of a table and bind the Stata and R columns side by side
stata_replay_table <- function(stem) {
  ref <- read_stata_reference(stem)
  replayed <- do.call(rbind, lapply(seq_len(nrow(ref)), function(i) {
    stata_replay(ref[i, , drop = FALSE])
  }))
  cbind(ref, replayed)
}

# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Grid 5: comparing the algebra with the fit taken out of the picture
# ---------------------------------------------------------------------------

#' Build R parameters from Stata's own fitted variance components
#'
#' Everything here is on Stata's fitted axis (time already divided by scale),
#' so the caller works with the integer schedule directly and no rescaling is
#' involved anywhere. That is the point: with identical inputs on both sides,
#' any remaining difference in var_tte, N or power is a defect in Sigma*, X* or
#' F* rather than a difference between two REML optimisers.
stata_manual_params <- function(fitrow) {
  comparator <- switch(fitrow$model,
                       obs_nocont = "none",
                       obs_cases  = "healthy",
                       rct        = "treated")
  slope_params_manual(
    slope            = fitrow$slope,
    sigma2_intercept = fitrow$v_intercept,
    sigma2_slope     = fitrow$v_slope,
    sigma_cov        = fitrow$cov_islope,
    sigma2_residual  = fitrow$v_residual,
    slope_comparator = if (comparator == "none") NA_real_ else fitrow$slope_comp,
    comparator       = comparator
  )
}

#' Match every row of a grid to the fit it was computed from
#'
#' Joined on the metadata rather than on a tag, so grid 5 and the other grids
#' stay independent: the key is exactly the set of things that can change a fit.
stata_join_fits <- function(grid, fits) {
  key <- function(x) paste(x$dataset, x$model, x$scale, x$subset, x$contvar,
                           sep = "|")
  idx <- match(key(grid), key(fits))
  list(grid = grid[!is.na(idx), , drop = FALSE],
       fits = fits[idx[!is.na(idx)], , drop = FALSE])
}

#' Format the offending rows of a comparison as a readable block
#'
#' A grid of several hundred rows is useless as several hundred separate
#' expectations: the failure that matters is "which rows disagree, and by how
#' much", so the tests make one expectation per quantity and print the table.
stata_mismatch_report <- function(bad, cols, label) {
  if (nrow(bad) == 0) return("")
  keep <- c("tag", "dataset", "model", "scale", "subset", "sched", "drops",
            "effin", "alpha", "mode", cols)
  keep <- keep[keep %in% names(bad)]
  txt <- utils::capture.output(print(bad[, keep, drop = FALSE], row.names = FALSE))
  paste0(label, ": ", nrow(bad), " row(s) disagree\n", paste(txt, collapse = "\n"))
}

#' Relative difference that degrades to absolute near zero
rel_diff <- function(a, b) {
  scale <- pmax(abs(a), abs(b), 1e-12)
  abs(a - b) / scale
}
